# Site settings
title: hello world
email: kfldevðŸµoutlookðŸµcom
description: > # this means to ignore newlines until "baseurl:"
    Mostly random coding stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username: kflu

# Build settings
# kramdown doesn't have c# syntax highlighting when using fenced code "```"
# markdown: kramdown
